name: Build RpcClient

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # Build RpcClient
      - name: Restore dependencies for RpcClient
        run: msbuild RpcClient/RpcClient.sln/t:restore
        continue-on-error: true
        shell: pwsh
        id: restore-RpcClient

      - name: Build log
        if: failure()
        run: Get-Content RpcClient/RpcClient.sln*.log-Tail 100

      - name: Upload artifact for RpcClient
        if: successful()
        uses: actions/upload-artifact@v2
        with:
          name: RpcClient-output
          path: |
            RpcClient/**/bin/Release/*

  