name: Build all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022  # Windows with Visual Studio 2022 for .NET Framework

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up MSBuild
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # Build RpcClient
      - name: Restore dependencies RpcClient
        run: msbuild RpcClient/RpcClient.sln /t:Restore
        shell: pwsh

      - name: Build RpcClient
        run: msbuild RpcClient/RpcClient.sln /p:Configuration=Release
        shell: pwsh

      # Upload RpcClient artifacts
      - name: Upload RpcClient artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RpcClient
          path: RpcClient/bin/Release/*

      # Build SprintCSP
      - name: Restore dependencies SprintCSP
        run: msbuild SprintCSP/SprintCSP.sln /t:Restore
        shell: pwsh

      - name: Build SprintCSP
        run: msbuild SprintCSP/SprintCSP.sln /p:Configuration=Release
        shell: pwsh

      # Upload SprintCSP artifacts
      - name: Upload SprintCSP artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SprintCSP
          path: SprintCSP/bin/Release/*

      # Create a release (only on push to main)
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      # Zip RpcClient output
      - name: Zip RpcClient
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: Compress-Archive -Path RpcClient/bin/Release/* -DestinationPath RpcClient.zip
        shell: pwsh

      # Zip SprintCSP output
      - name: Zip SprintCSP
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: Compress-Archive -Path SprintCSP/bin/Release/* -DestinationPath SprintCSP.zip
        shell: pwsh

      # Upload zipped files to the release
      - name: Upload Release Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.create_release.outputs.upload_url }} RpcClient.zip --clobber
          gh release upload ${{ steps.create_release.outputs.upload_url }} SprintCSP.zip --clobber
        shell: pwsh
        
