name: Build all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches all history for proper tag counting
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
      
      # Build RpcClient
      - name: Restore dependencies RpcClient
        run: msbuild RpcClient/RpcClient.sln /t:Restore
        shell: pwsh
      
      - name: Build RpcClient
        run: msbuild RpcClient/RpcClient.sln /p:Configuration=Release
        shell: pwsh
      
      # Build SprintCSP
      - name: Restore dependencies SprintCSP
        run: msbuild SprintCSP/SprintCSP.sln /t:Restore
        shell: pwsh
      
      - name: Build SprintCSP
        run: msbuild SprintCSP/SprintCSP.sln /p:Configuration=Release
        shell: pwsh
      
      # Upload artifacts directly from correct paths
      - name: Upload RpcClient
        uses: actions/upload-artifact@v4
        with:
          name: RpcClient
          path: RpcClient/x64/Release/RpcClient.exe
          
      - name: Upload SprintCSP
        uses: actions/upload-artifact@v4
        with:
          name: SprintCSP
          path: SprintCSP/x64/Release/SprintCSP.dll
      
      # Create release with correct file paths and proper tag incrementation
      - name: Create Release and Upload Files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Generate tag with incremental build number
          $date = Get-Date -Format "yyyy.MM.dd"
          $existingTags = git tag -l "v$date.*"
          $buildNumber = 0
          
          if ($existingTags) {
            # Extract max build number and increment
            $buildNumbers = $existingTags | ForEach-Object { 
              if ($_ -match "v$date\.(\d+)$") { 
                [int]$Matches[1] 
              } 
            }
            $maxBuildNumber = ($buildNumbers | Measure-Object -Maximum).Maximum
            $buildNumber = $maxBuildNumber + 1
          }
          
          $newTag = "v$date.$buildNumber"
          echo "Creating release with tag: $newTag"
          
          # Create zip files
          New-Item -ItemType Directory -Force -Path ./release
          Copy-Item ./RpcClient/x64/Release/RpcClient.exe ./release/
          Copy-Item ./SprintCSP/x64/Release/SprintCSP.dll ./release/
          Compress-Archive -Path ./release/* -DestinationPath ./release-files.zip -Force
          
          # Create release with zipped files
          gh release create $newTag "./release-files.zip" --title "Release $newTag" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
