name: Build RpcClient

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022  # Use a Windows runner with Visual Studio 2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up MSBuild for Visual Studio 2019
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore dependencies
      - name: Restore dependencies
        run: msbuild RpcClient/RpcClient.sln /t:Restore
        shell: pwsh

      # Build the solution
      - name: Build solution
        run: msbuild RpcClient/RpcClient.sln /p:Configuration=Release
        shell: pwsh

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RpcClient-output
          path: |
            RpcClient/**/Release/*
