name: Build Multiple Programs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8' # Adjust to your .NET version

      # Build RpcClient
      - name: Restore dependencies for RpcClient
        run: dotnet restore RpcClient/RpcClient.sln

      - name: Build solution for RpcClient
        run: dotnet build RpcClient/RpcClient.sln --configuration Release

      - name: Upload artifact for RpcClient
        uses: actions/upload-artifact@v2
        with:
          name: RpcClient-output
          path: |
            RpcClient/**/bin/Release/*

      # Build SprintCSP
      - name: Restore dependencies for SprintCSP
        run: dotnet restore SprintCSP/SprintCSP.sln

      - name: Build solution for SprintCSP
        run: dotnet build SprintCSP/SprintCSP.sln --configuration Release

      - name: Upload artifact for SprintCSP
        uses: actions/upload-artifact@v2
        with:
          name: SprintCSP-output
          path: |
            SprintCSP/**/bin/Release/*
